### ISSUE TITLE
Error: Embedding on GPU failed.  CUDA out of memory.

### ISSUE THREAD

**Issue by 000generic** [BernhoferM/TMbed#11]
Hi!

I have 921 genome-scale proteomes I working with for TMbed annotation. Using an initial subset of genomes, I am finding some genomes are annotated to completion without throwing an error - while others are partially processed but then an error is thrown:

Embedding on GPU failed.

CUDA out of memory. Tried to allocate 37.90 GiB. GPU 0 has a total capacity of 79.14 GiB of which 35.20 GiB is free. Including non-PyTorch memory, this process has 43.93 GiB memory in use. Of the allocated memory 41.43 GiB is allocated by PyTorch, and 2.00 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

Moving T5Encoder to CPU.

/tmp/slurmd/job49150654/slurm_script: line 85: 4177513 Killed                  tmbed predict --batch-size 1 -f ../../../../databases/gigantic_october2024/genomesdb_species940/genomesdb/fastas-species67/Holozoa_Choanozoa_Choanoflagellata_Craspedida_Salpingoecidae_Monosiga_brevicollis_MX1___431895-ncbi_GCF_000002865.3-downloaded_20241011-gene_models_T1.aa -p output/3-output/tmbed-Holozoa_Choanozoa_Choanoflagellata_Craspedida_Salpingoecidae_Monosiga_brevicollis_MX1 --use-gpu
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=49150654.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.

To run TMbed I am using the following:

`tmbed predict --batch-size 1 -f ../../../../databases/gigantic_october2024/genomesdb_species940/genomesdb/fastas-species67/Holozoa_Choanozoa_Choanoflagellata_Craspedida_Salpingoecidae_Monosiga_brevicollis_MX1___431895-ncbi_GCF_000002865.3-downloaded_20241011-gene_models_T1.aa -p output/3-output/tmbed-Holozoa_Choanozoa_Choanoflagellata_Craspedida_Salpingoecidae_Monosiga_brevicollis_MX1 --use-gpu &&
`

The failing genome in this case has only 9,202 sequences - vs a genome with 19,944 sequences completed. Also I have batch-size set to 1, per a recommendation you posted on a different issue for memory problems. In the documentation here it indicates around 15 Gb RAM is needed for TMbed - so I'm unclear why TMbed is requesting 37 Gb from the system.  
`
Here is an example sequence from its proteome fasta:

`>g_MONBRDRAFT_13249-t_000-p_XP_001751197.1-n_Holozoa_Choanozoa_Choanoflagellata_Craspedida_Salpingoecidae_Monosiga_brevicollis_MX1
MRGRGDRGGRAECGGARRGVALGPAEDVAADVEIVKARAESAGLHLQPSKSRFYMPCRHSASITAMKSVLPDAVRETANTGMTVLGTPIGRREWMKKQLNDKAKHIAGKLNDMLTTGVSLQALLTAMQYVPSLINHLYTLPPSLT
`

No idea if this is relevant - but is it possible there is a very long sequence genomes that are throwing errors that causes the memory request by TMbed to be so large? Our GPUs are limited to 80 Gb, so its not possible to expand memory further.

Any guidance or advice on this would be greatly appreciated! Thank you :) Eric

**Comment by BernhoferM** [comment]
Hi Eric,

This sounds indeed like an issue with a very long sequence. Reducing the batch size to 1 means that each sequence is processed one-by-one (setting it to 1 restricts batches to 1 residue, or one whole sequence if longer; which is always the case). However, the memory requirements still scale roughly quadratically with sequence length. Thus, super long sequences (10s of thousands of residues, like TITIN) will even fail on the biggest GPUs.

With the CPU fallback, you can still try to process them on CPU and normal RAM. However, this has two downsides:
1) It will take much longer to compute.
2) It will require even more RAM as the computation has to switch from 16-bit floats to 32-bit floats, i.e. roughly doubling the memory requirements.

It seems that this long sequence was even too much for the regular RAM available on the machine as the process was killed by the system ("Some of your processes may have been killed by the cgroup out-of-memory handler").

My suggestion would be to check for very long sequences and maybe remove them from the set; or try to process them on another high-RAM machine (on CPU), if available and you have the time. By default, TMbed processes sequences from shortest to longest. Thus, you can estimate which sequence length is too long for your GPU.

Regards
Michael
