### ISSUE TITLE
Versioning 

### ISSUE THREAD

**Issue by jowodo** [BernhoferM/TMbed#3]
Hi, 

please tag a version. This makes the software more reproducible. https://stackoverflow.com/questions/18216991/create-a-tag-in-a-github-repository

Thanks

**Comment by BernhoferM** [comment]
Hi,

thank you for the reminder. I had forgotten to put a version tag onto the initial release.

I have tagged the current commit with the v1.0.0 tag as there haven't been any changes to the prediction model since its release.

**Comment by jowodo** [comment]
Great thank you!
