### ISSUE TITLE
extra step to download model 

### ISSUE THREAD

**Issue by jowodo** [BernhoferM/TMbed#4]
it would be nice to be able to download the model with a `--download-model` option. 
I'm trying to install this software centrally. Downloading the model currently requires a fasta file. This was my work around: 
```
git lfs install
git clone https://huggingface.co/Rostlab/prot_t5_xl_half_uniref50-enc $PATH_TO_TMBED/tmbed/t5
rm -rf $PATH_TO_TMBED/tmbed/t5/.git
```
would be nice to do this (or similar) instead: 
```
tmbed --download-model
```

**Comment by BernhoferM** [comment]
Thanks to @cerebis you can now use `tmbed download` to download the ProtT5 model files.
Note that this will also instantiate the Encoder, which will help to check if the files are readable (i.e., complete and uncorrupted).
