### ISSUE TITLE
installation using Python 3.8.3

### ISSUE THREAD

**Issue by pietermonsieurs** [BernhoferM/TMbed#6]
Hi,
Is is possible to install the software using Python 3.8.3? The computing node I want to use is not yet upgraded to Python 3.9
Thanks!
Pieter

`pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing xxx/xxx/xxx/xxx/tmbed
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
ERROR: Package 'tmbed-1.0.0' requires a different Python: 3.8.3 not in '>=3.9,<4.0'`

**Comment by BernhoferM** [comment]
Hi. The requirements are based on the development/test platform that I've used. However, I think that the required packages are also compatible with Python 3.8; in fact, TMbed should also be quite flexible regarding the versions of those packages.

My suggestion would be to install the required packages (whatever is the most recent version supported by Python 3.8) and see if TMbed runs, e.g., by using it as a python module (`python -m tmbed`).

Required packages: h5py, numpy, sentencepiece, torch, tqdm, transformers, typer
