### ISSUE TITLE
assert len(prediction) == len(sequence)

### ISSUE THREAD

**Issue by smilenaderi** [BernhoferM/TMbed#8]
I get this error

████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1121/1121 [1:52:24<00:00,  6.02s/it]
Traceback (most recent call last):

  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,

  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)

  File "/vol2/ismail/tmbedv/tmbedf/tmbed/__main__.py", line 19, in <module>
    run()

  File "/vol2/ismail/tmbedv/tmbedf/tmbed/tmbed.py", line 413, in run
    app()

  File "/vol2/ismail/tmbedv/tmbedf/tmbed/tmbed.py", line 247, in predict
    write_3_line(output_file, proteins, predictions, pred_map)

  File "/vol2/ismail/tmbedv/tmbedf/tmbed/tmbed.py", line 374, in write_3_line
    assert len(prediction) == len(sequence)

**Comment by BernhoferM** [comment]
Hi. Could you please provide some more information about the input and used parameters to run TMbed?
If possible, the input FASTA file would be great (you can send it to me via email, if you do not want to share it publicly).

One possible reason I can think of is that the embeddings do not quite match the protein sequences (in length). Did you generate the embeddings with TMbed, or did you download pre-computed embeddings from somewhere else?

**Comment by smilenaderi** [comment]
I ran it with default settings:

`python3 -m tmbed predict -f q/test555A.fasta -p q/aligned555-2A.pred --no-use-gpu`




Here is input:
>seq-0-A
MKKIL--LLLLLLLLLSSCSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS-----
>seq-0-B
MK--LQQL------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------RYIVE
>seq-1-A
MSKIILLLLLLLSSSSA------QAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA----
>seq-1-B
----------------ATFDIVNQ-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------CTFT
>seq-2-A
M-----ASSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS----
>seq-2-B
MGREDKA----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------AWKA
>seq-3-A
M--------LKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK-
>seq-3-B
MTRRYWNIDL----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------E
>seq-4-A
MK-LLLLLLLLLSSSAAAP--AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA-----
>seq-4-B
--FL--------------PPCA-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------YKGTC
>seq-5-A
MKLLLLLLLL---SSS-------AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA-
>seq-5-B
----------YDPS--PLQDFCVA--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------D
>seq-6-A
MKLLLLLLLLLL---SSSALAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE---------
>seq-6-B
------------HGVS----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------GHGQHGVHG
>seq-7-A
MKVR-SSVKPMCE-KCKVIRRNGRVLV
>seq-7-B
MKVRPS-VKPMC-DK------------
>seq-8-A
MK-L-------L-LLLLLLSLSLSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
>seq-8-B
--FLIIRRPIVLGLL--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by smilenaderi** [comment]
@BernhoferM  Thank you for your reply. Actually these are aligned sequences from Needle culstal pairwise alignments

**Comment by BernhoferM** [comment]
Ah, I see the issue. The protein sequences may contain only amino acids, but no gaps ("-") or other special characters.

It also seem like the headers in your FASTA file are missing the ">" character at the start of each header line. Though those might have just been lost when you posted your input data here.

See [here](https://github.com/BernhoferM/TMbed/blob/main/examples/sample.fasta) for an example FASTA file.

Finally, many of those protein sequences look rather odd, i.e., they contain only a few different amino acids and very long stretches of repeats. Are those artificially generated?

**Comment by smilenaderi** [comment]
That's becayse I want to compare transmbebrence for two sequences. I aligned them to make them the same length and then run TMBED.

Fasta is correct, it's displaying different here. Yes they are generated sequences.

Is there any way to compare TMBED similarity for two sequences?

**Comment by BernhoferM** [comment]
The ProtT5 encoder only handles continuous sequences of amino acids. This is also the reason for the error `assert len(prediction) == len(sequence)` as the raw sequence (with gaps) is longer than the computed embedding (without gaps).

If you want to align/compare TMbed's predictions, you'd first have to generate the predictions for the full sequences without gaps. Afterwards you can use your alignment to compare the corresponding predictions for the aligned positions.
